MERGE INTO ROLE
    KEY(ROLE_ID)
VALUES (1, 'ADMIN'), (2, 'USER');

/*MERGE INTO CUSTOMER(ID, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, USER_NAME, ACTIVE)
VALUES (1, 'adminuser1@gamil.com','John', 'Johnson','$2y$10$x3BYtMKQI9alyMUfG5ezo.yzCmW1YnmkHTOLX4eTsapE9zZYY1dVO', 'adminUser1',1);

MERGE INTO USER_ROLE KEY (USER_ID)
VALUES (1, 1)*/